
title: Cafeteria Tematica
email: japarcana@isise.com
description: >- # this means to ignore newlines until "baseurl:"
  Cafeteria tematica es un lugar donde encontraras un ambiente calido
  donde podras disfrutar de los platos de la epoca de los 50's,
baseurl: "/myNewSite" # the subpath of your site, e.g. /blog
url: "https://Akim0423.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PMA
github_username:  Akim0423

# Build settings
theme: minima
plugins:
  - jekyll-feed

text: Texto Nuevo